# Generated by Django 2.2.7 on 2019-12-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Select_unit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ac',
            old_name='Ac_Location',
            new_name='Ac_Latitude',
        ),
        migrations.AddField(
            model_name='ac',
            name='Ac_Longitude',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changeinac',
            name='current_swing',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
