# Generated by Django 2.2.7 on 2019-12-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Select_unit', '0002_auto_20191205_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fan_name', models.CharField(max_length=255)),
                ('Fan_Latitude', models.CharField(max_length=255)),
                ('Fan_Longitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeInFAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_speed', models.IntegerField()),
                ('current_swing', models.IntegerField()),
                ('Name_of_changeMaker', models.CharField(max_length=255)),
                ('FAN_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Select_unit.FAN')),
            ],
        ),
    ]
