# Generated by Django 2.2.7 on 2019-12-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Select_unit', '0005_bulb_changeinbulb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeinbulb',
            name='Bulb_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Select_unit.Bulb'),
        ),
    ]
