# Generated by Django 2.2.7 on 2019-12-06 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Select_unit', '0006_auto_20191206_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smart_Wifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wifi_name', models.CharField(max_length=255)),
                ('Wifi_Latitude', models.CharField(max_length=255)),
                ('Wifi_Longitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeInWifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.IntegerField()),
                ('NumberOfAllowedConnections', models.IntegerField()),
                ('Bandwidth', models.CharField(max_length=20)),
                ('Name_of_changeMaker', models.CharField(max_length=255)),
                ('Wifi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Select_unit.Smart_Wifi')),
            ],
        ),
    ]
